# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0002_auto_20171109_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='portgroup',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privateirsservice',
            name='edge_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicirsservice',
            name='edge_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
