# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0006_auto_20171228_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='mx_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
    ]
