# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0013_auto_20180116_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateirsservice',
            name='wan_ip',
        ),
        migrations.RemoveField(
            model_name='publicirsservice',
            name='wan_ip',
        ),
        migrations.AddField(
            model_name='privateirsservice',
            name='ip_wan',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicirsservice',
            name='ip_wan',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
