# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0016_logicalunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicalunit',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
