# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0017_logicalunit_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateirsservice',
            name='sco_logical_unit',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicirsservice',
            name='sco_logical_unit',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicirsservice',
            name='vxrail_logical_unit',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
