# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0019_auto_20180305_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='portgroup',
            name='dvportgroup_id',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
