# Generated by Django 2.0.7 on 2019-05-28 18:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('client_name', models.CharField(max_length=50)),
                ('service_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=50)),
                ('service_state', models.CharField(max_length=50)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_state', models.CharField(blank=True, max_length=50)),
                ('op_type', models.CharField(max_length=30)),
                ('device', django.contrib.postgres.fields.jsonb.JSONField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Service')),
            ],
        ),
    ]
