# Generated by Django 2.0.7 on 2018-07-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_task_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='NidTransitionTask',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('worker.task',),
        ),
        migrations.CreateModel(
            name='ScoTransitionTask',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('worker.task',),
        ),
        migrations.RenameField(
            model_name='task',
            old_name='config',
            new_name='params',
        ),
        migrations.AddField(
            model_name='task',
            name='op_type',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
    ]
