# Generated by Django 2.0.7 on 2018-08-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_task_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MxCpelessIrsTask',
        ),
        migrations.CreateModel(
            name='MxCpelessTask',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('worker.task',),
        ),
    ]
