# Generated by Django 2.0.7 on 2018-08-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0008_auto_20180813_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='strategy',
        ),
    ]
