version: '3.5'
services:
 postgres:
  image: postgres:latest
  container_name: "postgres"
 charles:
  restart: always
 jeangrey:
  restart: always
  depends_on:
   - postgres
 worker:
  restart: always
  depends_on:
   - postgres
 inventory:
  depends_on:
   - postgres
 core:
  restart: always