version: '3.5'
services:
 core:
  build: ./core/
  restart: always
  ports:
   - "8000:8000"
  volumes:
   - ./core:/app
   - ./createsuperuser.py:/usr/src/app/createsuperuser.py
  env_file:
   - ./.env
  command: "python manage.py runserver"
