version: '3.5'
services:
 postgres:
  image: postgres:latest
  container_name: "postgres"
  env_file:
   - ./.env
  volumes:
   - ./volumes/postgres:/var/lib/postgresql/data
   - ./db/postgres/10-init.sql:/docker-entrypoint-initdb/10-init.sql
  ports:
   - 5432:5432
 charles:
  build: ./charles/
  restart: always
  ports:
   - "8004:8000"
  volumes:
   - ./charles:/app
   - ./createsuperuser.py:/usr/src/app/createsuperuser.py
  environment:
   - ENV=development
  depends_on:
   - postgres
  env_file:
   - ./.env
  command: bash -c "python manage.py migrate && python manage.py runserver"
 core:
  build: ./core/
  restart: always
  ports:
   - "8000:8000"
  volumes:
   - ./core:/app
   - ./createsuperuser.py:/usr/src/app/createsuperuser.py
  environment:
   - ENV=development
  depends_on:
   - postgres
  env_file:
   - ./.env
  command: bash -c "python manage.py migrate && python manage.py runserver"
 jeangrey:
  build: ./jeangrey/
  restart: always
  ports:
   - "8002:8000"
  volumes:
   - ./jeangrey:/app
   - ./createsuperuser.py:/usr/src/app/createsuperuser.py
  environment:
   - ENV=development
  depends_on:
   - postgres
  env_file:
   - ./.env
  command: bash -c "python manage.py migrate && python manage.py runserver"
 worker:
  build: ./worker/
  restart: always
  ports:
   - "8003:8000"
  volumes:
   - ./worker:/app
   - ./createsuperuser.py:/usr/src/app/createsuperuser.py
  environment:
   - ENV=development
  depends_on:
   - postgres
  env_file:
   - ./.env
  command: bash -c "python manage.py migrate && python manage.py runserver"
 inventory:
  build: ./inventory/
  restart: always
  ports:
   - "8001:8000"
  volumes:
   - ./inventory:/app
   - ./createsuperuser.py:/usr/src/app/createsuperuser.py
  environment:
   - ENV=development
  depends_on:
   - postgres
  env_file:
   - ./.env
  command: bash -c "python manage.py migrate && python manage.py runserver"
networks:
 default:
  name: onsa