version: '3.5'
services:
 postgres:
  image: postgres:latest
  container_name: "postgres"
  env_file:
   - ./.env
  volumes:
   - ./volumes/postgres:/var/lib/postgresql/data
   - ./db/postgres/10-init.sql:/docker-entrypoint-initdb/10-init.sql
  ports:
   - 5432:5432
 charles:
  build: ./charles/
  restart: always
  ports:
   - "8004:8004"
  volumes:
   - ./charles:/app
   - ./createsuperuser.py:/usr/src/app/createsuperuser.py
  environment:
   - ENV=development
   - PORT=8004
  depends_on:
   - postgres
  env_file:
   - ./.env
  command: bash -c "chmod +x createsuperuser.py
            && python manage.py migrate
            && ./createsuperuser.py
            && python manage.py runserver 0.0.0.0:$PORT"
 core:
  build: ./core/
  restart: always
  ports:
   - "8000:8000"
  volumes:
   - ./core:/app
   - ./createsuperuser.py:/usr/src/app/createsuperuser.py
  environment:
   - ENV=development
   - PORT=8000
  depends_on:
   - postgres
  env_file:
   - ./.env
  command: bash -c "chmod +x createsuperuser.py
            && python manage.py migrate
            && ./createsuperuser.py
            && python manage.py runserver 0.0.0.0:$PORT"
networks:
 default:
  name: onsa