version: '3.5'
services:
 postgres:
  image: postgres:latest
  container_name: "postgres"
  env_file:
   - ./env/.dev.env
  volumes:
   - ./volumes/postgres:/var/lib/postgresql/data
   - ./db/postgres/10-init.sql:/docker-entrypoint-initdb/10-init.sql
  ports:
   - 5433:5432
 charles:
  build: ./charles/
  ports:
   - "8004:8000"
  volumes:
   - ./charles:/app
   - ./scripts:/usr/src/app/scripts
  env_file:
   - ./env/.dev.env
  command: ./scripts/dev/run.sh
 jeangrey:
  build: ./jeangrey/
  restart: always
  ports:
   - "8002:8000"
  volumes:
   - ./jeangrey:/app
   - ./scripts:/usr/src/app/scripts
  depends_on:
   - postgres
  env_file:
   - ./env/.dev.env
  command: ./scripts/dev/run.sh
 worker:
  build: ./worker/
  restart: always
  ports:
   - "8003:8000"
  volumes:
   - ./worker:/app
   - ./scripts:/usr/src/app/scripts
  depends_on:
   - postgres
  env_file:
   - ./env/.dev.env
  command: ./scripts/dev/run.sh
 inventory:
  build: ./inventory/
  restart: always
  ports:
   - "8001:8000"
  volumes:
   - ./inventory:/app
   - ./scripts:/usr/src/app/scripts
  depends_on:
   - postgres
  env_file:
   - ./env/.dev.env
  command: ./scripts/dev/run.sh
 core:
  build: ./core/
  restart: always
  ports:
   - "8000:8000"
  volumes:
   - ./core:/app
   - ./scripts:/usr/src/app/scripts
  env_file:
   - ./env/.dev.env
  command: ./scripts/dev/run.sh