version: '3.5'
services:
 postgres:
  env_file:
   - ./env/.prod.env
  ports:
   - 5432:5432
 charles:
  ports:
   - "8004:8000"
  env_file:
   - ./env/.prod.env
 jeangrey:
  ports:
   - "8002:8000"
  env_file:
   - ./env/.prod.env
 worker:
  build: ./worker/
  ports:
   - "8003:8000"
  env_file:
   - ./env/.prod.env
 inventory:
  restart: always
  ports:
   - "8001:8000"
  env_file:
   - ./env/.prod.env
 core:
  ports:
   - "80:8000"
  env_file:
   - ./env/.prod.env