# Generated by Django 2.0.7 on 2018-07-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=50)),
                ('service_state', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=50)),
            ],
        ),
    ]
