# Generated by Django 2.0.7 on 2018-07-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(default='Some', max_length=50),
            preserve_default=False,
        ),
    ]
