# Generated by Django 2.0.7 on 2018-10-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charles', '0002_service_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='location',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.AlterField(
            model_name='service',
            name='service_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
