# Generated by Django 2.0.7 on 2018-11-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charles', '0004_service_target_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deployment_mode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
