# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-28 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deviceType', models.CharField(blank=True, max_length=50)),
                ('mgmtIP', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('client', models.CharField(blank=True, max_length=50)),
                ('uplinkInterface', models.CharField(max_length=50)),
                ('accessNodeId', models.CharField(max_length=4)),
                ('qinqOuterVlan', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('port', models.CharField(max_length=50, null=True)),
                ('used', models.BooleanField(default=False)),
                ('client', models.CharField(max_length=50)),
                ('accessNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.AccessNode')),
            ],
        ),
        migrations.CreateModel(
            name='ClientNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deviceType', models.CharField(blank=True, max_length=50)),
                ('mgmtIP', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('serialNumber', models.CharField(blank=True, max_length=50)),
                ('client', models.CharField(blank=True, max_length=50)),
                ('service', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LogicalUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_unit_id', models.PositiveSmallIntegerField()),
                ('used', models.BooleanField(default=False)),
                ('locations', models.ManyToManyField(to='inventory.Location')),
            ],
        ),
        migrations.CreateModel(
            name='NsxEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deviceType', models.CharField(blank=True, max_length=50)),
                ('mgmtIP', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('client', models.CharField(blank=True, max_length=50)),
                ('edgeName', models.CharField(max_length=50)),
                ('ipWan', models.CharField(max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpticalNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deviceType', models.CharField(blank=True, max_length=50)),
                ('mgmtIP', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('serialNumber', models.CharField(blank=True, max_length=50)),
                ('client', models.CharField(blank=True, max_length=50)),
                ('hwId', models.CharField(blank=True, max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Portgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_tag', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('used', models.BooleanField(default=False)),
                ('dvportgroup_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RouterNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deviceType', models.CharField(blank=True, max_length=50)),
                ('mgmtIP', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('client', models.CharField(blank=True, max_length=50)),
                ('privateWanIp', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VirtualVmwPod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deviceType', models.CharField(blank=True, max_length=50)),
                ('mgmtIP', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('client', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('transportZoneName', models.CharField(blank=True, max_length=50)),
                ('clusterName', models.CharField(blank=True, max_length=50)),
                ('datastoreId', models.CharField(blank=True, max_length=50)),
                ('resourcePoolId', models.CharField(blank=True, max_length=50)),
                ('datacenterId', models.CharField(blank=True, max_length=50)),
                ('uplinkPg', models.CharField(blank=True, max_length=50)),
                ('uplinkPgId', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VlanTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_tag', models.CharField(max_length=50, null=True)),
                ('used', models.BooleanField(default=False)),
                ('accessPorts', models.ManyToManyField(to='inventory.AccessPort')),
            ],
        ),
        migrations.AddField(
            model_name='portgroup',
            name='virtualVmwPod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.VirtualVmwPod'),
        ),
        migrations.AddField(
            model_name='clientnode',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Location'),
        ),
        migrations.AddField(
            model_name='accessnode',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Location'),
        ),
    ]
