# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-28 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessnode',
            name='client',
        ),
        migrations.RemoveField(
            model_name='nsxedge',
            name='client',
        ),
        migrations.RemoveField(
            model_name='routernode',
            name='client',
        ),
        migrations.RemoveField(
            model_name='virtualvmwpod',
            name='client',
        ),
        migrations.AlterField(
            model_name='accessport',
            name='client',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
