# Generated by Django 2.0.7 on 2018-08-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessnode',
            name='vendor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clientnode',
            name='vendor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='nsxedge',
            name='vendor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='routernode',
            name='vendor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='virtualvmwpod',
            name='vendor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
