# Generated by Django 2.0.7 on 2018-08-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='access_port_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
