# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180628_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessport',
            name='client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
