# Generated by Django 2.0.7 on 2018-08-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_services_access_port_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNodePort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deviceType', models.CharField(blank=True, max_length=50)),
                ('mgmtIP', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('vendor', models.CharField(blank=True, max_length=50)),
                ('interface_name', models.CharField(blank=True, max_length=50)),
                ('used', models.BooleanField(default=False)),
                ('service_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='accessport',
            name='client',
        ),
        migrations.RemoveField(
            model_name='accessport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clientnode',
            name='id',
        ),
        migrations.AlterField(
            model_name='clientnode',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='clientnodeport',
            name='client_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ClientNode'),
        ),
        migrations.AddField(
            model_name='clientnodeport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Location'),
        ),
    ]
