# Generated by Django 2.0.7 on 2018-09-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180827_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='pop_size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
