# Generated by Django 2.0.7 on 2018-07-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_vlantag_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logicalunit',
            name='used',
        ),
        migrations.AlterField(
            model_name='logicalunit',
            name='logical_unit_id',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='vlantag',
            name='vlan_tag',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
