# Generated by Django 2.0.7 on 2018-09-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_location_pop_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessnode',
            name='uplink_ports',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clientnodeport',
            name='uplink_port',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
