# Generated by Django 2.0.7 on 2018-07-11 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180705_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logicalunit',
            name='locations',
        ),
        migrations.AddField(
            model_name='logicalunit',
            name='routerNodes',
            field=models.ManyToManyField(to='inventory.RouterNode'),
        ),
        migrations.AddField(
            model_name='nsxedge',
            name='portgroup',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.Portgroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='virtualvmwpod',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Location'),
        ),
    ]
