# Generated by Django 2.0.7 on 2018-07-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20180711_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logicalunit',
            name='routerNodes',
            field=models.ManyToManyField(blank=True, to='inventory.RouterNode'),
        ),
        migrations.AlterField(
            model_name='vlantag',
            name='accessPorts',
            field=models.ManyToManyField(blank=True, to='inventory.AccessPort'),
        ),
    ]
