# Generated by Django 2.0.7 on 2018-09-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20180903_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vrf',
            fields=[
                ('rt', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=50)),
                ('locations', models.ManyToManyField(blank=True, to='inventory.Location')),
            ],
        ),
        migrations.RenameField(
            model_name='services',
            old_name='serviceid',
            new_name='service_id',
        ),
        migrations.AddField(
            model_name='services',
            name='site_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
