# Generated by Django 2.0.7 on 2018-07-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20180713_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessnode',
            name='logicalUnitId',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
    ]
