# Generated by Django 2.0.7 on 2018-09-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180904_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrf',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vrf',
            name='service_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
