# Generated by Django 2.0.7 on 2018-07-25 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_accessnode_logicalunitid'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualvmwpod',
            name='routerNode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.RouterNode'),
        ),
    ]
