# Generated by Django 2.0.7 on 2018-09-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20180907_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='vrf',
            name='service_id',
        ),
        migrations.AddField(
            model_name='vrf',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vrf',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
