# Generated by Django 2.0.7 on 2018-08-08 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_virtualvmwpod_uplinkinterface'),
    ]

    operations = [
        migrations.CreateModel(
            name='VlantagAccessports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.AccessPort')),
            ],
            options={
                'db_table': 'inventory_vlantag_accessPorts',
            },
        ),
        migrations.AlterField(
            model_name='vlantag',
            name='accessPorts',
            field=models.ManyToManyField(blank=True, through='inventory.VlantagAccessports', to='inventory.AccessPort'),
        ),
        migrations.AddField(
            model_name='vlantagaccessports',
            name='vlantag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.VlanTag'),
        ),
        migrations.AlterUniqueTogether(
            name='vlantagaccessports',
            unique_together={('vlantag', 'accessport')},
        ),
    ]
