# Generated by Django 2.0.7 on 2018-09-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20180907_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='routernode',
            name='loopback',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
