# Generated by Django 2.0.7 on 2018-08-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20180808_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlantagaccessports',
            name='serviceid',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
