# Generated by Django 2.0.7 on 2018-09-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_routernode_loopback'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrf',
            name='client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vrf',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
