# Generated by Django 2.0.7 on 2018-08-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_vlantagaccessports_serviceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientnode',
            name='service',
        ),
        migrations.AddField(
            model_name='vlantagaccessports',
            name='bandwidth',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vlantagaccessports',
            name='client_node_port',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vlantagaccessports',
            name='sn_client_node',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vlantagaccessports',
            name='serviceid',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
