# Generated by Django 2.0.7 on 2018-09-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20180910_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='vrf_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
