# Generated by Django 2.0.7 on 2018-09-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_services_vrf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='vrf_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
