# Generated by Django 2.0.7 on 2018-09-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20180912_2025'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='services',
            unique_together={('vlantag', 'access_node', 'access_port_id')},
        ),
    ]
