# Generated by Django 2.0.7 on 2018-09-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20180921_1822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Products',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='service_id',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='logicalunit',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
