# Generated by Django 2.0.7 on 2018-09-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20180924_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='portgroup',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
