# Generated by Django 2.0.7 on 2018-10-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_portgroup_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessnode',
            old_name='accessNodeId',
            new_name='access_node_id',
        ),
        migrations.RenameField(
            model_name='accessport',
            old_name='accessNode',
            new_name='access_node',
        ),
    ]
