# Generated by Django 2.0.7 on 2018-10-17 19:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('service_state', models.CharField(default='PENDING', max_length=15)),
                ('service_type', models.CharField(max_length=30)),
                ('bandwidth', models.CharField(max_length=50, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50)),
                ('router_node_id', models.CharField(max_length=10)),
                ('logical_unit_id', models.CharField(max_length=10)),
                ('access_node_id', models.CharField(max_length=10)),
                ('access_port_id', models.CharField(max_length=50)),
                ('vlan_id', models.CharField(max_length=10)),
                ('client_node_sn', models.CharField(max_length=50, null=True)),
                ('client_node_port', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CpeIrs',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jeangrey.Service')),
                ('wan_network', models.CharField(max_length=50)),
                ('public_network', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('jeangrey.service',),
        ),
        migrations.CreateModel(
            name='CpelessIrs',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jeangrey.Service')),
                ('public_network', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('jeangrey.service',),
        ),
        migrations.CreateModel(
            name='CpelessMpls',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jeangrey.Service')),
                ('vrf_id', models.CharField(blank=True, max_length=50, null=True)),
                ('autonomous_system', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(65000), django.core.validators.MaxValueValidator(65500)])),
                ('client_network', models.CharField(blank=True, max_length=50)),
            ],
            bases=('jeangrey.service',),
        ),
        migrations.CreateModel(
            name='CpeMpls',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jeangrey.Service')),
                ('autonomous_system', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(65000), django.core.validators.MaxValueValidator(65500)])),
                ('vrf_id', models.CharField(blank=True, max_length=50, null=True)),
                ('wan_network', models.CharField(max_length=50)),
                ('client_network', models.CharField(blank=True, max_length=50)),
            ],
            bases=('jeangrey.service',),
        ),
        migrations.CreateModel(
            name='VcpeIrs',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jeangrey.Service')),
                ('vcpe_logical_unit_id', models.CharField(max_length=10)),
            ],
            bases=('jeangrey.service',),
        ),
        migrations.AddField(
            model_name='service',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jeangrey.Client'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('vlan_id', 'access_node_id', 'access_port_id')},
        ),
    ]
