# Generated by Django 2.0.7 on 2018-11-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeangrey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpeirs',
            name='wan_network',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cpempls',
            name='client_network',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cpempls',
            name='wan_network',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
