# Generated by Django 2.0.7 on 2018-10-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeangrey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='client_node_port',
            new_name='client_port_id',
        ),
    ]
