# Generated by Django 2.0.7 on 2018-10-18 15:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeangrey', '0002_auto_20181017_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vpls',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jeangrey.Service')),
                ('vrf_id', models.CharField(blank=True, max_length=50, null=True)),
                ('autonomous_system', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(65000), django.core.validators.MaxValueValidator(65500)])),
            ],
            bases=('jeangrey.service',),
        ),
        migrations.AddField(
            model_name='service',
            name='location_id',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
