# Generated by Django 2.0.7 on 2018-11-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeangrey', '0002_auto_20181105_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cpeirs',
            name='prefix',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cpeirs',
            name='public_network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cpeirs',
            name='wan_network',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cpelessirs',
            name='prefix',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cpelessirs',
            name='public_network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cpelessmpls',
            name='client_network',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cpelessmpls',
            name='vrf_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cpempls',
            name='client_network',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cpempls',
            name='vrf_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cpempls',
            name='wan_network',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='access_node_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='access_port_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='bandwidth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='client_node_sn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='client_port_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='location_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='logical_unit_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='router_node_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='vlan_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vcpeirs',
            name='portgroup_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vcpeirs',
            name='prefix',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vcpeirs',
            name='public_network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vcpeirs',
            name='vcpe_logical_unit_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vcpeirs',
            name='wan_ip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vpls',
            name='vrf_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
