# Generated by Django 2.0.7 on 2018-10-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeangrey', '0003_auto_20181018_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='location_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='logical_unit_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='prefix',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='router_node_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_state',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
