# Generated by Django 2.0.7 on 2018-10-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeangrey', '0004_auto_20181019_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcpeirs',
            name='portgroup_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vcpeirs',
            name='wan_ip',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vcpeirs',
            name='vcpe_logical_unit_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
