# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0003_auto_20171122_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='datastore_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hub',
            name='resource_pool_id',
            field=models.CharField(max_length=50),
        ),
    ]
