# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0010_auto_20171229_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='datacenter_id',
            field=models.CharField(default='datacenter-2', max_length=50),
            preserve_default=False,
        ),
    ]
