# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0014_auto_20180116_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='vxrail_ae_interface',
            field=models.CharField(default='ae1', max_length=50),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='hub',
        #     name='vxrail_outer_vlan',
        #     field=models.CharField(default='21', max_length=50),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='sco',
            name='sco_ae_interface',
            field=models.CharField(default='ae1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sco',
            name='sco_id',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sco',
            name='sco_outer_vlan',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
