# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0018_auto_20180219_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateirsservice',
            name='product_identifier',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicirsservice',
            name='product_identifier',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
