# Generated by Django 2.0.7 on 2018-08-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_service_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='model',
            field=models.CharField(default='asd', max_length=30),
            preserve_default=False,
        ),
    ]
