# Generated by Django 2.0.7 on 2018-08-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_auto_20180808_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MxCpelessTask',
        ),
        migrations.DeleteModel(
            name='MxVcpeTask',
        ),
        migrations.DeleteModel(
            name='NidTransitionTask',
        ),
        migrations.DeleteModel(
            name='NsxTask',
        ),
        migrations.DeleteModel(
            name='ScoTransitionTask',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.AddField(
            model_name='task',
            name='strategy',
            field=models.CharField(default='asd', max_length=30),
            preserve_default=False,
        ),
    ]
