# Generated by Django 2.0.7 on 2018-08-13 14:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_auto_20180810_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='model',
        ),
        migrations.RemoveField(
            model_name='task',
            name='params',
        ),
        migrations.AddField(
            model_name='task',
            name='device',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
