# Generated by Django 2.0.7 on 2018-08-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='bandwidth',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='client_node_port',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='client_node_sn',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='service_identifier',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='service_state',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='vrf',
        ),
    ]
