# Generated by Django 2.0.7 on 2018-07-05 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('ip_management', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='CpePort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Cpe')),
            ],
        ),
        migrations.CreateModel(
            name='PublicIrsService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_identifier', models.CharField(max_length=50)),
                ('bandwidth', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('NOT_CONFIGURED', 'NOT_CONFIGURED'), ('CONFIGURING', 'CONFIGURING'), ('CONFIGURED', 'CONFIGURED')], default='NOT_CONFIGURED', max_length=15)),
                ('edge_name', models.CharField(blank=True, max_length=50)),
                ('ip_wan', models.GenericIPAddressField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
                ('cpe_port', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CpePort')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='nsxpublicirsservice',
            name='client',
        ),
        migrations.AddField(
            model_name='cpelessirsservice',
            name='bandwidth',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpelessirsservice',
            name='status',
            field=models.CharField(choices=[('NOT_CONFIGURED', 'NOT_CONFIGURED'), ('CONFIGURING', 'CONFIGURING'), ('CONFIGURED', 'CONFIGURED')], default='NOT_CONFIGURED', max_length=15),
        ),
        migrations.AddField(
            model_name='cpelessmplsservice',
            name='bandwidth',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpelessmplsservice',
            name='status',
            field=models.CharField(choices=[('NOT_CONFIGURED', 'NOT_CONFIGURED'), ('CONFIGURING', 'CONFIGURING'), ('CONFIGURED', 'CONFIGURED')], default='NOT_CONFIGURED', max_length=15),
        ),
        migrations.DeleteModel(
            name='NsxPublicIrsService',
        ),
        migrations.AddField(
            model_name='cpelessmplsservice',
            name='cpe_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CpePort'),
        ),
    ]
