# Generated by Django 2.0.7 on 2018-07-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180705_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CpeLessMplsService',
            new_name='MplsService',
        ),
    ]
