# Generated by Django 2.0.7 on 2018-08-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180816_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='some',
        ),
        migrations.AlterField(
            model_name='service',
            name='prefix',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='public_network',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='vrf',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicecperelations',
            name='bandwidth',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicecperelations',
            name='prefix',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicecperelations',
            name='vrf',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
