# Generated by Django 2.0.7 on 2018-08-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180821_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
