# Generated by Django 2.0.7 on 2018-08-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180816_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecperelations',
            name='client',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
