# Generated by Django 2.0.7 on 2018-08-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicecperelations_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpe',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='servicecperelations',
            name='service_state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
