# Generated by Django 2.0.7 on 2018-07-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180717_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpelessirsservice',
            name='service_type',
            field=models.CharField(choices=[('PUBLIC_IRS_VCPE', 'PUBLIC_IRS_VCPE'), ('MPLS', 'MPLS'), ('VPLS', 'VPLS'), ('PUBLIC_IRS_CPELESS', 'PUBLIC_IRS_CPELESS')], default='PUBLIC_IRS_CPELESS', max_length=30),
        ),
        migrations.AddField(
            model_name='mplsservice',
            name='service_type',
            field=models.CharField(choices=[('PUBLIC_IRS_VCPE', 'PUBLIC_IRS_VCPE'), ('MPLS', 'MPLS'), ('VPLS', 'VPLS'), ('PUBLIC_IRS_CPELESS', 'PUBLIC_IRS_CPELESS')], default='PUBLIC_IRS_CPELESS', max_length=30),
        ),
        migrations.AddField(
            model_name='publicirsservice',
            name='service_type',
            field=models.CharField(choices=[('PUBLIC_IRS_VCPE', 'PUBLIC_IRS_VCPE'), ('MPLS', 'MPLS'), ('VPLS', 'VPLS'), ('PUBLIC_IRS_CPELESS', 'PUBLIC_IRS_CPELESS')], default='PUBLIC_IRS_CPELESS', max_length=30),
        ),
    ]
