# Generated by Django 2.0.7 on 2018-08-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180816_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecperelations',
            name='service_identifier',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
