# Generated by Django 2.0.7 on 2018-07-18 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180717_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=50, unique=True)),
                ('product_identifier', models.CharField(max_length=50)),
                ('bandwidth', models.PositiveSmallIntegerField()),
                ('service_type', models.CharField(choices=[('PUBLIC_IRS_VCPE', 'PUBLIC_IRS_VCPE'), ('MPLS', 'MPLS'), ('VPLS', 'VPLS'), ('PUBLIC_IRS_CPELESS', 'PUBLIC_IRS_CPELESS')], default='PUBLIC_IRS_CPELESS', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('REQUESTED', 'REQUESTED'), ('COMPLETED', 'COMPLETED'), ('ERROR', 'ERROR')], default='PENDING', max_length=15)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cpelessirsservice',
            name='public_prefix',
            field=models.PositiveSmallIntegerField(default=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicirsservice',
            name='public_prefix',
            field=models.PositiveSmallIntegerField(default=24),
            preserve_default=False,
        ),
    ]
