# Generated by Django 2.0.7 on 2018-07-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180718_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpelessirsservice',
            name='service_id',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='mplsservice',
            name='service_id',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='publicirsservice',
            name='service_id',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='servicefactory',
            name='service_id',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
