# Generated by Django 2.0.7 on 2018-08-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_servicecperelations_service_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecperelations',
            name='service_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
