# Generated by Django 2.0.7 on 2018-07-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180718_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpelessirsservice',
            old_name='status',
            new_name='service_state',
        ),
        migrations.RenameField(
            model_name='mplsservice',
            old_name='status',
            new_name='service_state',
        ),
        migrations.RenameField(
            model_name='publicirsservice',
            old_name='status',
            new_name='service_state',
        ),
        migrations.RenameField(
            model_name='servicefactory',
            old_name='status',
            new_name='service_state',
        ),
        migrations.AlterField(
            model_name='cpelessirsservice',
            name='service_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mplsservice',
            name='service_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='publicirsservice',
            name='service_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='servicefactory',
            name='service_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
