# Generated by Django 2.0.7 on 2018-08-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180723_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpelessirsservice',
            name='service_type',
            field=models.CharField(choices=[('vcpe_irs', 'vcpe_irs'), ('MPLS', 'MPLS'), ('VPLS', 'VPLS'), ('PUBLIC_IRS_CPELESS', 'PUBLIC_IRS_CPELESS')], default='PUBLIC_IRS_CPELESS', max_length=30),
        ),
        migrations.AlterField(
            model_name='mplsservice',
            name='service_type',
            field=models.CharField(choices=[('vcpe_irs', 'vcpe_irs'), ('MPLS', 'MPLS'), ('VPLS', 'VPLS'), ('PUBLIC_IRS_CPELESS', 'PUBLIC_IRS_CPELESS')], default='PUBLIC_IRS_CPELESS', max_length=30),
        ),
        migrations.AlterField(
            model_name='publicirsservice',
            name='cpe_port',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CpePort'),
        ),
        migrations.AlterField(
            model_name='publicirsservice',
            name='ip_wan',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicirsservice',
            name='service_type',
            field=models.CharField(choices=[('vcpe_irs', 'vcpe_irs'), ('MPLS', 'MPLS'), ('VPLS', 'VPLS'), ('PUBLIC_IRS_CPELESS', 'PUBLIC_IRS_CPELESS')], default='PUBLIC_IRS_CPELESS', max_length=30),
        ),
        migrations.AlterField(
            model_name='servicefactory',
            name='service_type',
            field=models.CharField(choices=[('vcpe_irs', 'vcpe_irs'), ('MPLS', 'MPLS'), ('VPLS', 'VPLS'), ('PUBLIC_IRS_CPELESS', 'PUBLIC_IRS_CPELESS')], default='PUBLIC_IRS_CPELESS', max_length=30),
        ),
    ]
