# Generated by Django 2.0.7 on 2018-08-21 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180821_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecperelations',
            name='client_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicecperelations',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Client'),
        ),
    ]
