# Generated by Django 2.0.7 on 2018-09-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180829_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='vrf',
            new_name='vrf_name',
        ),
        migrations.AddField(
            model_name='service',
            name='wan_ip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(max_length=30),
        ),
    ]
