# Generated by Django 2.0.7 on 2018-09-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180910_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='public_network',
            new_name='client_network',
        ),
    ]
