# Generated by Django 2.0.7 on 2018-09-13 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180911_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='autonomous_system',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(65000), django.core.validators.MaxValueValidator(65500)]),
        ),
    ]
