# Generated by Django 2.0.7 on 2018-09-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180914_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='product_identifier',
        ),
    ]
