# Generated by Django 2.0.7 on 2018-09-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_service_product_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='bandwidth',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
