# Generated by Django 2.0.7 on 2018-10-10 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20181009_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='access_node',
        ),
        migrations.RemoveField(
            model_name='service',
            name='access_node_port',
        ),
        migrations.RemoveField(
            model_name='service',
            name='bandwidth',
        ),
        migrations.RemoveField(
            model_name='service',
            name='client_node_port',
        ),
        migrations.RemoveField(
            model_name='service',
            name='client_node_sn',
        ),
        migrations.RemoveField(
            model_name='service',
            name='location',
        ),
        migrations.RemoveField(
            model_name='service',
            name='vrf_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='wan_ip',
        ),
    ]
