# Generated by Django 2.0.7 on 2018-10-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181010_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vrf_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
