# Generated by Django 2.0.7 on 2018-10-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_service_vrf_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='client',
        ),
        migrations.DeleteModel(
            name='CpeLessIrsService',
        ),
        migrations.DeleteModel(
            name='MplsService',
        ),
        migrations.DeleteModel(
            name='VcpePublicIrsService',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
