DeviceModel.create(brand:"Transition Networks Inc",model:"S4224")
DeviceModel.create(brand:"Transition Networks Inc",model:"SM24-100SFP-AH")
DeviceModel.create(brand:"Transition Networks Inc",model:"SM24-1000SFP-AH")
DeviceModel.create(brand:"Transition Networks Inc",model:"MRV OA2000")
DeviceModel.create(brand:"Transition Networks Inc",model:"MIL-SM4004TG")
DeviceModel.create(brand:"Net2Edge",model:"LIB4424")
DeviceModel.create(brand:"Juniper Networks",model:"EX4550")
DeviceModel.create(brand:"Juniper Networks",model:"MX104")