from jeangrey.views.client_service import ClientServiceView
from jeangrey.views.clients import ClientView
from jeangrey.views.customer_locations import CustomerLocationView
from jeangrey.views.customer_locations_access_ports import CustomerLocationAccessPortsView
from jeangrey.views.services import ServiceView