# Generated by Django 2.0.7 on 2018-12-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=50)),
                ('service_state', models.CharField(blank=True, max_length=50, null=True)),
                ('target_state', models.CharField(blank=True, max_length=50, null=True)),
                ('deployment_mode', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
