# Generated by Django 2.1.8 on 2019-04-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeangrey', '0003_auto_20181107_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cuic',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
