# Generated by Django 2.0.7 on 2019-05-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeangrey', '0004_client_cuic'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='gts',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
