# Generated by Django 2.0.7 on 2019-06-03 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeangrey', '0007_auto_20190530_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='access_node_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='access_port_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='customer_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jeangrey.CustomerLocation'),
        ),
        migrations.AlterField(
            model_name='service',
            name='vlan_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
