# Generated by Django 2.0.7 on 2019-06-04 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeangrey', '0008_auto_20190603_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpelessirs',
            name='service_ptr',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jeangrey.Service'),
        ),
    ]
