# Generated by Django 2.0.7 on 2019-06-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeangrey', '0009_auto_20190604_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpempls',
            name='loopback',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
