# Generated by Django 2.0.7 on 2019-07-24 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeangrey', '0010_cpempls_loopback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legacy',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jeangrey.Service')),
            ],
            options={
                'abstract': False,
            },
            bases=('jeangrey.service',),
        ),
        migrations.AlterField(
            model_name='customerlocation',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
