# Generated by Django 2.0.7 on 2018-11-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20181030_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_of_life_date', models.CharField(blank=True, max_length=50, null=True)),
                ('end_of_sale_date', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='clientnode',
            name='customer_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
