from core.views.clients import client_view
from core.views.customer_locations import customer_locations_view
from core.views.locations import locations_view
from core.views.logical_units import logical_units_view
from core.views.client_customer_locations_access_ports import client_customer_location_access_ports_view
from core.views.service_resources import service_resources_view
from core.views.vlans import vlans_view
from core.views.vrfs import vrfs_view
from core.views.service import service_view
from core.views.service_activation import service_activation_view
from core.views.ldap_jwt import *
from core.views.monitoring import status_monitoring_view
from core.views.traffic_monitoring import traffic_monitoring_view
from core.views.multiclient_access_ports import multiclient_access_ports
from core.views.device_models import device_models_view
