# Generated by Django 2.0.7 on 2018-08-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180821_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecperelations',
            name='bandwidth',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='servicecperelations',
            name='client_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='servicecperelations',
            name='client_node_port',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecperelations',
            name='client_node_sn',
            field=models.CharField(default='123', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecperelations',
            name='prefix',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='servicecperelations',
            name='product_identifier',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='servicecperelations',
            name='service_state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='servicecperelations',
            name='service_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='servicecperelations',
            name='vrf',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
