# Generated by Django 2.0.7 on 2018-08-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180821_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('vcpe_irs', 'vcpe_irs'), ('mpls', 'mpls'), ('vpls', 'vpls'), ('cpeless_irs', 'cpeless_irs')], default='cpeless_irs', max_length=30),
        ),
    ]
