# Generated by Django 2.0.7 on 2018-08-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180822_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='access_node',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='access_node_port',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(choices=[('CENTRO', 'CENTRO'), ('RETIRO', 'RETIRO'), ('SANTA_FE', 'SANTA_FE'), ('PALERMO', 'PALERMO')], default='cpeless_irs', max_length=30),
        ),
    ]
