# Generated by Django 2.0.7 on 2018-08-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180822_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecperelations',
            name='bandwidth',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='client',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='client_node_port',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='client_node_sn',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='product_identifier',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='service_state',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='servicecperelations',
            name='vrf',
        ),
    ]
