# Generated by Django 2.0.7 on 2018-08-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180823_2033'),
        ('core', '0006_auto_20180824_1247'),
    ]

    operations = [
    ]
