# Generated by Django 2.0.7 on 2018-08-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20180824_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpe',
            name='id',
        ),
        migrations.AlterField(
            model_name='cpe',
            name='serial_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cpeport',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
