# Generated by Django 2.0.7 on 2018-09-14 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_service_autonomous_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='autonomous_system',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(65000), django.core.validators.MaxValueValidator(65500)]),
        ),
    ]
