# Generated by Django 2.0.7 on 2018-09-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180924_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='bandwidth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
