# Generated by Django 2.0.7 on 2018-10-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180924_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_state',
            field=models.CharField(default='PENDING', max_length=15),
        ),
    ]
