# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('transport_zone_name', models.CharField(max_length=50)),
                ('cluster_name', models.CharField(max_length=50)),
                ('datastore_id', models.IntegerField()),
                ('resource_pool_id', models.IntegerField()),
                ('uplink_ip', models.GenericIPAddressField()),
                ('uplink_pg', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Portgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_tag', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsx.Hub')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateIrsService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_segment', models.GenericIPAddressField()),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsx.Hub')),
            ],
        ),
        migrations.CreateModel(
            name='PublicIrsService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_segment', models.GenericIPAddressField()),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsx.Hub')),
            ],
        ),
    ]
