# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateirsservice',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nsx.Client'),
        ),
        migrations.AddField(
            model_name='publicirsservice',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nsx.Client'),
        ),
    ]
