# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_cpelessmplsservice_client_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpelessirsservice',
            name='ip_wan',
        ),
        migrations.RemoveField(
            model_name='cpelessmplsservice',
            name='ip_wan',
        ),
    ]
