# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0004_auto_20171122_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpWan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
                ('network', models.GenericIPAddressField()),
                ('mask', models.PositiveSmallIntegerField()),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsx.Hub')),
            ],
        ),
        migrations.CreateModel(
            name='Sco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsx.Hub')),
            ],
        ),
        migrations.CreateModel(
            name='ScoPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('used', models.BooleanField(default=False)),
                ('sco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsx.Sco')),
            ],
        ),
        migrations.RemoveField(
            model_name='privateirsservice',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='publicirsservice',
            name='hub',
        ),
        migrations.AddField(
            model_name='privateirsservice',
            name='ip_wan',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='privateirsservice',
            name='portgroup',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='nsx.Portgroup'),
        ),
        migrations.AddField(
            model_name='publicirsservice',
            name='ip_wan',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='publicirsservice',
            name='portgroup',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='nsx.Portgroup'),
        ),
        migrations.AddField(
            model_name='privateirsservice',
            name='sco_port',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='nsx.ScoPort'),
        ),
        migrations.AddField(
            model_name='publicirsservice',
            name='sco_port',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='nsx.ScoPort'),
        ),
    ]
