# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180622_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsxpublicirsservice',
            name='hub',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Hub'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpelessirsservice',
            name='hub',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Hub'),
        ),
        migrations.AlterField(
            model_name='cpelessmplsservice',
            name='hub',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Hub'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='cluster_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hub',
            name='datacenter_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hub',
            name='datastore_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hub',
            name='resource_pool_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hub',
            name='transport_zone_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hub',
            name='uplink_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hub',
            name='uplink_pg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hub',
            name='uplink_pg_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='nsxpublicirsservice',
            name='portgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Portgroup'),
        ),
    ]
