# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0007_hub_mx_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoport',
            name='port',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scoport',
            name='vlan_tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
