# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0008_auto_20171229_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateirsservice',
            name='portgroup',
        ),
        migrations.RemoveField(
            model_name='privateirsservice',
            name='sco_port',
        ),
        migrations.RemoveField(
            model_name='publicirsservice',
            name='portgroup',
        ),
        migrations.RemoveField(
            model_name='publicirsservice',
            name='sco_port',
        ),
    ]
