# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0011_hub_datacenter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ippublicsegment',
            name='mask',
        ),
        migrations.RemoveField(
            model_name='privateirsservice',
            name='ip_wan',
        ),
        migrations.RemoveField(
            model_name='publicirsservice',
            name='ip_wan',
        ),
        migrations.AddField(
            model_name='ippublicsegment',
            name='prefix',
            field=models.PositiveSmallIntegerField(default=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipwan',
            name='prefix',
            field=models.PositiveSmallIntegerField(default=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privateirsservice',
            name='wan_ip',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='nsx.IpWan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicirsservice',
            name='wan_ip',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='nsx.IpWan'),
            preserve_default=False,
        ),
    ]
