# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0012_auto_20180116_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ippublicsegment',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='publicirsservice',
            name='ip_segment',
        ),
        migrations.AddField(
            model_name='publicirsservice',
            name='public_network',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='nsx.IpPublicSegment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ipwan',
            name='network',
            field=models.CharField(max_length=50),
        ),
    ]
