# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0015_auto_20180124_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicalUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_unit_id', models.PositiveSmallIntegerField()),
                ('hubs', models.ManyToManyField(to='nsx.Hub')),
            ],
        ),
    ]
