# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0020_portgroup_dvportgroup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='uplink_pg_id',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
