# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0022_cpelessirsservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicIrsService',
            new_name='NsxPublicIrsService',
        ),
        migrations.RemoveField(
            model_name='privateirsservice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='privateirsservice',
            name='portgroup',
        ),
        migrations.RemoveField(
            model_name='privateirsservice',
            name='sco_port',
        ),
        migrations.RemoveField(
            model_name='cpelessirsservice',
            name='edge_name',
        ),
        migrations.RemoveField(
            model_name='cpelessirsservice',
            name='portgroup',
        ),
        migrations.AddField(
            model_name='cpelessirsservice',
            name='client_unit',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PrivateIrsService',
        ),
    ]
